// Code Generated by Sidekick is for learning and experimentation purposes only.
document.addEventListener('DOMContentLoaded', () => {
    const products = [
        { id: 1, name: 'Dress', price: 50 },
        { id: 2, name: 'Shoes', price: 80 },
        { id: 3, name: 'Bag', price: 120 }
    ];

    const recommendations = [
        { id: 4, name: 'Hat', price: 20 },
        { id: 5, name: 'Scarf', price: 30 }
    ];

    const cart = [];
    let currency = 'USD';
    const exchangeRates = {
        USD: 1,
        EUR: 0.85,
        GBP: 0.75
    };

    const productContainer = document.querySelector('.product-list');
    const recommendationContainer = document.querySelector('.recommendations');
    const cartContainer = document.querySelector('.cart-items');

    function renderProducts() {
        productContainer.innerHTML = '';
        products.forEach(product => {
            const productElement = document.createElement('div');
            productElement.classList.add('product');
            productElement.innerHTML = `
                <h3>${product.name}</h3>
                <p>Price: ${convertCurrency(product.price)}</p>
                <button onclick="addToCart(${product.id})">Add to Cart</button>
            `;
            productContainer.appendChild(productElement);
        });
    }

    function renderRecommendations() {
        recommendationContainer.innerHTML = '';
        recommendations.forEach(product => {
            const recommendationElement = document.createElement('div');
            recommendationElement.classList.add('recommendation');
            recommendationElement.innerHTML = `
                <h3>${product.name}</h3>
                <p>Price: ${convertCurrency(product.price)}</p>
                <button onclick="addToCart(${product.id})">Add to Cart</button>
            `;
            recommendationContainer.appendChild(recommendationElement);
        });
    }

    function renderCart() {
        cartContainer.innerHTML = '';
        cart.forEach(item => {
            const cartItemElement = document.createElement('div');
            cartItemElement.classList.add('cart-item');
            cartItemElement.innerHTML = `
                <h3>${item.name}</h3>
                <p>Price: ${convertCurrency(item.price)}</p>
                <button onclick="removeFromCart(${item.id})">Remove</button>
            `;
            cartContainer.appendChild(cartItemElement);
        });
    }

    function convertCurrency(amount) {
        return (amount * exchangeRates[currency]).toFixed(2) + ' ' + currency;
    }

    window.addToCart = function(productId) {
        const product = products.find(p => p.id === productId) || recommendations.find(p => p.id === productId);
        cart.push(product);
        renderCart();
    };

    window.removeFromCart = function(productId) {
        const productIndex = cart.findIndex(p => p.id === productId);
        if (productIndex > -1) {
            cart.splice(productIndex, 1);
            renderCart();
        }
    };

    document.getElementById('checkout-form').addEventListener('submit', (event) => {
        event.preventDefault();
        alert('Purchase Complete!');
        cart.length = 0;
        renderCart();
    });

    document.getElementById('currency').addEventListener('change', (event) => {
        currency = event.target.value;
        renderProducts();
        renderRecommendations();
        renderCart();
    });

    renderProducts();
    renderRecommendations();
});
